### ISSUE TITLE
Setting for adding a proxy level point tag in wavefront.conf

### ISSUE THREAD

**Issue by shahdhruvin** [wavefrontHQ/wavefront-proxy#245]
I am looking at the use-case where I will have to repeat the point tag addition rule for all the ports (3 for now we have) in the preprocessor_rules.html file.

For me this is a proxy level rule, not an collector agent level rule. 
Hence I started looking into wavefront.conf, tried out few things. and finally came to know that I need to actually apply this point tag rule in preprocessor_rules.

It is instinctive for this proxy level rule to be in wavefront.conf

Adam agreed to this logic over slack channel.
Adam Johnson [3:08 PM]
I agree, for a global thing like that wavefront.conf would be good, but I’m not sure the main conf file has any point tag controls.

And then as per Conor's suggestion - opening this PR

**Comment by shahdhruvin** [comment]
Looks like this is a lot of plumbing work required to apple a point tag at a proxy level.
In preprocessor - Apply identical rule per port (3 times)
And then apply logsIngestion changes too, may be again repeat tags there per counter, histogram or gauge?

**Comment by panghy** [comment]
@basilisk487 can you respond to the ticket?

**Comment by akodali18** [comment]
Closing this issue. Fixed with #503
