### ISSUE TITLE
Support "X-Debug" as a flag to indicate not dropping it as a part of its sampling.

### ISSUE THREAD

**Issue by akodali18** [wavefrontHQ/wavefront-proxy#416]

**Comment by akodali18** [comment]
Include support for https://github.com/jaegertracing/jaeger-client-java/blob/02252d99aa3ec2e7686e2ca7f92ede99013528eb/README.md#via-http-headers as well

**Comment by sushantdewan123** [comment]
Also need to support "X-B3-Debug"
