### ISSUE TITLE
Make 2878 port (the defacto default port) support http ingestion with format support

### ISSUE THREAD

**Issue by panghy** [wavefrontHQ/wavefront-proxy#506]
Essentially make the proxy behave exactly like direct ingestion via http/https to the wavefront service.

**Comment by panghy** [comment]
I will proceed with our Spring Boot integration assuming that WPC will be gone and everything will be WDIC in the future.

**Comment by basilisk487** [comment]
https://github.com/wavefrontHQ/wavefront-proxy/pull/510
