### ISSUE TITLE
Wavefront Proxy 9.7 Docker Container getting crashed due to OOM

### ISSUE THREAD

**Issue by arjunkchr** [wavefrontHQ/wavefront-proxy#623]
We have lately been observing WF Proxy Version 9.7 getting OOM'd. This is causing a back pressure on telegraf container and it sometimes results in telegraf container not being able to send metrics to WF Proxy. This results in missing metrics and alerts being triggered in Production. This was earlier not observed on WF Proxy version 9.2. 

Captured heap dump(using jmap) from WF Proxy running 9.7 from Production.
[heapdump_9.7_prod.bin.zip](https://github.com/wavefrontHQ/wavefront-proxy/files/6577103/heapdump_9.7_prod.bin.zip)

Happy to provide further information as required since this is a frequent occurrence now in Production. 

WF Proxy is running with 2GB Memory in Production with 1024 CPU.

**Comment by idrennanvmware** [comment]
Wavefront team - any thoughts on this?   We have had to roll back to 9.2 to remove this issue but we are now running "behind" in versions.
