### ISSUE TITLE
Docker container has a huge layer because of chown of /var

### ISSUE THREAD

**Issue by dimas** [wavefrontHQ/wavefront-proxy#685]
There is
```
RUN chown -R wavefront:wavefront /var
```
done when building Docker container - https://github.com/wavefrontHQ/wavefront-proxy/blob/master/proxy/docker/Dockerfile#L20
As docker does copy-on-write, this operation creates a huge layer - `docker image history` shows
```
<missing>      2 days ago   /bin/sh -c chown -R wavefront:wavefront /var    180MB     
```
which is quite a lot compared to seemingly innocent operation.

I suspect you do not need to change ownership to the entire `/var` hierarchy...

**Comment by laullon** [comment]
Fixed
