### ISSUE TITLE
no main manifest attribute for proxy-11.3-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by shivania2** [wavefrontHQ/wavefront-proxy#772]
I am upgarding to wavefront-proxy-11.3. Succesfully build the project locally, but for proxy-11.3-jar-with-dependencies.jar I am getting following error

$java -jar proxy-11.3-jar-with-dependencies.jar
$no main manifest attribute, in proxy-11.3-jar-with-dependencies.jar

Manifest file of proxy-11.3-jar-with-dependencies.jar has following content
`Manifest-Version: 1.0
Created-By: Plexus Archiver 4.2.1`

In wavefront-proxy 11.1 version we have proxy-11.1-uber.jar instead of proxy-11.3-jar-with-dependencies.jar 
Manifest file of proxy-11.1-uber.jar  has following content
`Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.6.3
Built-By: root
Build-Jdk: 11.0.12-internal
Main-Class: com.wavefront.agent.PushAgent
Multi-Release: true`

Due to the proxy-11.3-jar-with-dependencies.jar Main class error, not able to consume wavefront-proxy-11.3.

**Comment by thepeterstone** [comment]
Hi @shivania2 thanks for the report! The [release notes for 11.3](https://github.com/wavefrontHQ/wavefront-proxy/releases/tag/proxy-11.3) have been updated to mention that the jar to use is `proxy-11.3-spring-boot.jar` and `proxy-11.3-jar-with-dependencies.jar` is for internal use.

Please give it a go with the `proxy-11.3-spring-boot.jar` which shouldn't have this issue.

**Comment by shivania2** [comment]
Hi @thepeterstone ,
Does proxy-11.3-jar-with-dependencies.jar and proxy-11.3-spring-boot.jar have same functionality?

**Comment by shivania2** [comment]
Fixed the issue locally, hence closing this issue
